###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysql:
      image: mysql:8.0
      container_name: docker-symfony4-mysql
      working_dir: /application
      entrypoint: ['/entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
      volumes:
        - handball_api:/var/lib/mysql
      environment:
        - TZ=Europe/Paris
        - MYSQL_ROOT_PASSWORD=dinosaure76
        - MYSQL_DATABASE=handball_api
        - MYSQL_USER=handball_api
        - MYSQL_PASSWORD=handball_api
      ports:
        - "8002:3306"

    webserver:
      image: nginx:alpine
      container_name: docker-symfony4-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "8000:80"
      expose:
        - 80
      depends_on:
        - mysql
        - php-fpm

    php-fpm:
      build: phpdocker/php-fpm
      container_name: docker-symfony4-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

volumes:
  handball_api:
networks:
  default:
    external:
      name: nginx
